### ISSUE TITLE
GitHub Calendar Demo No Longer Working

### ISSUE THREAD

**Issue by jerrychong25** [IonicaBizau/github-calendar#134]
Hi all,

I would like to use GitHub Calendar plugin, as per sample demo in https://bloggify.github.io/github-calendar/example/.

However, I noticed the demo is no longer working as of today (7th February 2021), as per screenshot below: 
<img width="1085" alt="Screenshot 2021-02-07 at 6 33 19 PM" src="https://user-images.githubusercontent.com/15714095/107144007-2a7e2e00-6973-11eb-82f7-56a8bb47fef0.png">

Could help to fix this issue?

Thanks.

**Comment by jihoonkimtech** [comment]
Looks like everyone's been unable to use the calendar because of this error.

It's a problem caused by this error -> **TypeError: Cannot set property 'innerHTML'**
This error was mentioned in the previous issue #133.
You can get more detailed information from the issue above, so it would be good to refer to it!

**Comment by jerrychong25** [comment]
Thank you @jihoonkimtech and @IonicaBizau !
