### ISSUE TITLE
❗️ The numbers are not displayed correctly at the moment.

### ISSUE THREAD

**Issue by rsael** [IonicaBizau/github-calendar#157]
<img width="852" alt="Screenshot 2023-01-06 at 09 39 26" src="https://user-images.githubusercontent.com/57199115/210974084-76e38468-6049-489e-863e-3839e8502634.png">

**Comment by kamyarst** [comment]
Same problem

**Comment by kj-sh604** [comment]
**Reporting the same issue as well…**

It's also replicated on the [example instance](https://bloggify.github.io/github-calendar/example/) from the README.

Same goes on my [personal website](https://aedrielkylejavier.me/github.html).

**Comment by totoroot** [comment]
@rsael @kamyarst @kj-sh604 I've just opened a PR (https://github.com/IonicaBizau/github-calendar-parser/pull/25) with a fix for the parsing library.

Until it gets merged, consider setting the options `tooltips` and `globalstats` to `false` so that the graph on your site does not look as broken.

The levels itself are still correctly parsed, so the graph itself should still look fine.

**Comment by kj-sh604** [comment]
@totoroot yes, I did that on the day that I've noticed that it broke. Thank you very much for the work on the fix… super cool! much appreciated 😌

**Comment by alanmontgomery** [comment]
This is the same for me

**Comment by HeyMehedi** [comment]
This also happens to my website: https://heymehedi.com/

**Comment by IonicaBizau** [comment]
Sorry for the delay. I have just released a new version which fixes this. :)
