### ISSUE TITLE
Contributions showing as text, not squares 

### ISSUE THREAD

**Issue by masterneko** [IonicaBizau/github-calendar#169]
Hi, 

 This issue was first noticed on [Tabliss](https://github.com/joelshepherd/tabliss/issues/620) which depends on github-calendar. The contributions should be grey/green squares but appear as text.

![image](https://github.com/Bloggify/github-calendar/assets/53895123/fd4c946a-3b2f-4693-8b91-e4e83296f70c)

**Comment by TriAttack238** [comment]
I have the same problem. Thought it might have been caused by my updating to Windows 11, but it seems to be a new issue.

**Comment by Hyperboid** [comment]
Same issue here, also coming from Tabliss. Looks like it's coming from the hover text seen on the official page.

![Github Calendar](https://github.com/Bloggify/github-calendar/assets/23138363/f4fe7f34-f210-4c7f-9eff-8b08f604b44d)

**Comment by Anoerak** [comment]
Same issue on Firefox, Edge and Safari.

**Comment by sskartheekadivi** [comment]
Same issue with Windows 10 + Google Chrome.

**Comment by kelvinjou** [comment]
Same issue. Macbook & Iphone + Opera & Chrome.

**Comment by IonicaBizau** [comment]
Hey all! Thanks for reporting this. I’m currently recovering after a knee surgery, so I’m afraid I am not going to be able to push a fix to this but I’m happy to accept a pull request. Sorry for the inconvenience… Sent from my iPhoneOn 16 Jul 2023, at 11:23, Anørak ***@***.***> wrote:﻿
Same issue on Firefox, Edge and Safari.

**Comment by Jwashton** [comment]
I can't dig into it more right now, but to give somebody else a jump start:

It looks like this script [fetches](https://github.com/Bloggify/github-calendar/blob/76bbf989df237223851a034921681c236218deb1/lib/index.js#L90) the information from this proxied location: https://api.bloggify.net/gh-calendar/?username=Jwashton

And it looks like the script is expecting that response to [contain an SVG](https://github.com/Bloggify/github-calendar/blob/76bbf989df237223851a034921681c236218deb1/lib/index.js#L130), but it now contains an HTML table.

This means that a couple different things go wrong: in the browser console I get a `TypeError: svg is null` and in the CSS some critical selectors don't match because they're looking for `rect.class` instead of `td.class`.

Here's one potential [fix for the CSS issues](https://github.com/joelshepherd/tabliss/issues/620#issuecomment-1637130183) from @polypoyo .

**Comment by d-kleine** [comment]
I hope that there will be a hotfix in this repository soon 🙏 🤞

**Comment by IonicaBizau** [comment]
Sorry for the delay on solving this. This is finally fixed. 🎉

**Comment by d-kleine** [comment]
@IonicaBizau Just want to be sure, at least for me it looks not to be fully fixed yet:
* cells are colored, but no frame around each cells as before (see above)
* counters seem to be broken too
![grafik](https://github.com/Bloggify/github-calendar/assets/53251018/fa4be205-6947-4b92-bf04-3c4d2345ea28)

Also, when minimized, the week day labels intersect with the cells:
![grafik](https://github.com/Bloggify/github-calendar/assets/53251018/e83510c2-ef26-486a-9f23-49d1bd3b0607)

In the minimized view, could you please also make the [thumb element in horizontal scrollbar](https://i.stack.imgur.com/QpyZW.png) starting from the right side to show the latest contributions? Currently, the thumb starts from the left side, showing the latest contribs:
![grafik](https://github.com/Bloggify/github-calendar/assets/53251018/4c765df5-cd98-4e4c-b3ad-d546d189b8e0)

It would be better if the thumb could start from the right side, showing the most recent contribs:
![grafik](https://github.com/Bloggify/github-calendar/assets/53251018/d68d8386-da14-40b2-ae2c-1f32ebd32d39)

Also, in dark mode setting in the browser, the `global_stats` labels stay black:

White mode:
![grafik](https://github.com/Bloggify/github-calendar/assets/53251018/bfa5595a-04ac-4345-b47d-408940ac762f)

Dark mode:
![grafik](https://github.com/Bloggify/github-calendar/assets/53251018/31ad4f81-2a71-4c7f-a03b-3bda63474e83)


Please also see [your example in action](https://bloggify.github.io/github-calendar/example/)
