### ISSUE TITLE
Github heatmap not showing up anymore

### ISSUE THREAD

**Issue by shivam-bit** [IonicaBizau/github-calendar#172]
## Issue
Till few months back everything was working fine, but suddenly the heatmap stopped showing up.

<img width="1320" alt="Screenshot 2023-08-06 at 12 17 31 PM" src="https://github.com/Bloggify/github-calendar/assets/60030881/47a110aa-6e95-4ae8-aa71-087ba9efbcb8">

## Error
<img width="1320" alt="Screenshot 2023-08-06 at 12 17 43 PM" src="https://github.com/Bloggify/github-calendar/assets/60030881/5c11d69e-9320-4990-ab72-aec840c29b82">
<img width="1320" alt="Screenshot 2023-08-06 at 12 18 01 PM" src="https://github.com/Bloggify/github-calendar/assets/60030881/d9f904c6-35fa-4ccf-96d9-b50da4f3644c">

## PS
If i am disabling responsiveness by  `responsive: false` then following content is rendered without any errors on console but as you can see still the stats are completely missing.

<img width="1320" alt="Screenshot 2023-08-06 at 12 20 58 PM" src="https://github.com/Bloggify/github-calendar/assets/60030881/385a9ab0-5c19-4b6e-b502-3868d68b2da8">

**Comment by shivam-bit** [comment]
@IonicaBizau your help will be appreciated .

**Comment by SahilMayenkar** [comment]
This issue is related to #169.

The following comment (https://github.com/Bloggify/github-calendar/issues/169#issuecomment-1638288345) explains how the script fetches the information from a proxied location and is expecting the result to be an svg; however, it seems that the API at that location has recently changed and now returns an HTML table. This results in null type errors for anything referencing the svg, such as in the error you posted.

**Comment by pmanaktala** [comment]
Is there a fix that is out for it? It suddenly stopped working for me as well.

**Comment by jalopezg-git** [comment]
> Is there a fix that is out for it? It suddenly stopped working for me as well.

@pmanaktala, please, see https://github.com/Bloggify/github-calendar/pull/173.  The MR is essentially a first, preliminary fix.

**Comment by IonicaBizau** [comment]
Thank you for your contribution, @jalopezg-git! 🍰
